In [1]:
import numpy as np

In [2]:
myList = [1,2,3]
myArray = np.array(myList)
print(type(myList))
print(type(myArray))
print(myArray.shape)
print(myArray)

<class 'list'>
<class 'numpy.ndarray'>
(3,)
[1 2 3]


In [3]:
myList = [[1,2,3],[4,5,6]]
myArray = np.array(myList)

print(myArray)
print(myArray.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [4]:
print("Baris pertama: ", myArray[0])
print("Baris terakhir: ", myArray[1])

Baris pertama:  [1 2 3]
Baris terakhir:  [4 5 6]


In [5]:
print("Baris pertama kolom ketiga: ", myArray[0][2])

Baris pertama kolom ketiga:  3


In [7]:
print("Hasilnya: ", myArray[:,2])

Hasilnya:  [3 6]


In [10]:
myArray1 = np.array([2,2,2])
myArray2 = np.array([3,3,3])

print("Hasil dari perjumlahan array: ", myArray1 + myArray2)
print("Hasil dari perkalian array", myArray1 * myArray2)

Hasil dari perjumlahan array:  [5 5 5]
Hasil dari perkalian array [6 6 6]
